apiVersion: v1
kind: Service
metadata:
  labels: 
    app: backend-feed
  name: backend-feed
spec:
  selector:
    app: backend-feed
  ports:
    - name: "8080"
      targetPort: 8080
      port: 8080