apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
        api: external        
    spec:
      containers:
      - image: olaniyiogungbe/udagram-frontend:v2
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "256m"
          limits:
            cpu: "512m"                
      restartPolicy: Always

